
server:
  port: 8888
  servlet:
    context-path: /
spring:
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/wuye?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
  #    password: Wuzetao19971025@
  devtools:  # 热部署
    livereload:
      enabled: false
  mail:
    host: smtp.qq.com
    username: 1351645715@qq.com
    password: QFAQPLFQZRZBMVWQ
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson: # 时间格式转化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis
mybatis-plus:
  type-aliases-package: com.coderwzt.model
  mapper-locations: classpath:com/coderwzt/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

loginIndex: http://localhost:8888

